config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'contact' => 'pages#contact'
  get 'cv' => 'pages#cv'
  get 'works' => 'pages#works'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def cv
  end

  def works
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<style type="text/css">
    .footer {
        padding-top: 1%;
        padding-bottom: 1px;
        margin-top: 1%;
        border-top: 1px solid #eee;
    }
</style>

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
      </div>
      <div class="col-md-6">
        <p class="text-muted text-right">
          &copy;2015 Sulman Baig
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SULMAN', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My Works <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu" role="menu">-->
            <!--<li><a href="http://social.sulman.me/">Web App: Socialbook (Facebook like social network)</a></li>-->
            <!--<li><a href="http://fotolib.sulman.me/">Web App: FotoLib (Private Images Managing App)</a></li>-->
            <!--<li><a href="http://scholarshipnetwork.info/">Web App: SSN (Scholarship website)</a></li>-->
            <!--<li><a href="http://stukdo.sulman.me/">Web App: Stukdo (todo list)</a></li>-->
            <!--<li><a href="http://estuk.sulman.me/">Web App: eStuk (2-sided bookstore)</a></li>-->
            <!--<li><a href="http://demo.sulman.me/">Website: Startup Demo Page</a></li>-->
            <!--<li class="divider"></li>-->
            <!--<li><a href="https://play.google.com/store/search?q=sulman%20baig" target="_blank">My Android Apps</a></li>-->
          <!--</ul>-->
        <!--</li>-->
        <li><%= link_to 'My Works', works_path %></li>
        <li><%= link_to 'My CV', cv_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="google-site-verification" content="5GsAwQl6zFoQ7oLqhUqOUEfCDuH6mHZQTwfEoNHCR1w" />
  <title><%= yield :title %> | Sulman Baig</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <style type="text/css">
      <%= yield :styles %>
  </style>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="fb-root"></div>
<script>window.fbAsyncInit = function() {
    FB.init({
        appId      : '401575483380285',
        xfbml      : true,
        version    : 'v2.3'
    });
};

(function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<header>
  <%= render 'layouts/header' %>
</header>

<section>
  <%= yield :section %>
</section>

<footer>
  <%= render 'layouts/footer' %>
</footer>

<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        <%= yield :scripts %>
    });
</script>
</body>
</html>

app/views/pages/_myworks.html.erb
<div class="container-fluid">
  <div class="row link-ex">

    <!-- Tweeter link -->
    <%= link_to "http://tweet.sulman.me/" do %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="offer offer-radius offer-primary">
            <div class="shape">
              <div class="shape-text">
                new
              </div>
            </div>
            <div class="offer-content">
              <h3 class="lead">
                Tweeter
              </h3>
              <p>
                http://tweet.sulman.me/<br>
                Twitter clone social network
              </p>
            </div>
          </div>
        </div>
    <% end %>

    <!-- note link -->
    <%= link_to "http://note.sulman.me/" do %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="offer offer-radius offer-primary">
            <div class="shape">
              <div class="shape-text">
                new
              </div>
            </div>
            <div class="offer-content">
              <h3 class="lead">
                Key-Note
              </h3>
              <p>
                http://note.sulman.me/<br>
                Note taking and sharing app.
              </p>
            </div>
          </div>
        </div>
    <% end %>

    <!-- fotolib link -->
    <%= link_to "http://fotolib.sulman.me/" do %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="offer offer-radius offer-primary">
            <div class="offer-content">
              <h3 class="lead">
                FotoLib
              </h3>
              <p>
                http://fotolib.sulman.me/<br>
                Private photos managing and sharing app
              </p>
            </div>
          </div>
        </div>
    <% end %>

    <!-- others link -->
    <%= link_to works_path do %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="offer offer-radius offer-primary">
            <div class="offer-content">
              <h3 class="lead">
                Other Works ...
              </h3>
              <p>
                http://sulman.me/works/<br>
                Click here to see my other projects
              </p>
            </div>
          </div>
        </div>
    <% end %>

  </div>
</div>

app/views/pages/contact.html.erb
<% content_for :title, 'Contact' %>

<style>
    <% content_for :styles do %>
        body {
            background-color: #efefef;
            min-height: auto;
        }
    <% end %>
</style>

<section>
  <% content_for :section do %>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 text-center">
            <h3>Contact Details</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <a href="mailto:sulman.baig.ee@gmail.com"><i class="fa fa-envelope-o"></i> sulman.baig.ee@gmail.com</a><br>
            <a href="https://github.com/sulmanhotmail"><i class="fa fa-github-square"></i> sulmanhotmail</a><br>
            <a href="http://twitter.com/intent/tweet?screen_name=sulmanweb"><i class="fa fa-twitter-square"></i> @sulmanweb</a><br>
          </div>
          <div class="col-sm-4">
            <a href="https://www.facebook.com/tiredofbeingnumb"><i class="fa fa-facebook-square"></i> Sulman Baig</a><br>
            <a href="https://plus.google.com/u/0/+SulmanBaigweb/about"><i class="fa fa-google-plus-square"></i> +SulmanBaigweb</a><br>
            <a href="https://www.linkedin.com/in/sulmanbaig"><i class="fa fa-linkedin-square"></i> sulmanbaig</a><br>
          </div>
          <div class="col-sm-4">
            <a href="https://www.youtube.com/channel/UCkecwtFwuPlVPKUhgI8bzvw"><i class="fa fa-youtube-play"></i> Sulman Baig</a><br>
            <a href="skype:sulman1990@hotmail.com?userinfo"><i class="fa fa-skype"></i> sulman1990@hotmail.com</a><br>
            <a href="tel:+393423293236"><i class="fa fa-phone-square"></i> +39 342 329 3236</a><br>
          </div>
        </div>
      </div>
  <% end %>
</section>

<script>
    <% content_for :scripts do %>
    <% end %>
</script>

app/views/pages/home.html.erb
<% content_for :title, 'Home' %>

<style>
    <% content_for :styles do %>
    body {
        background-color: #efefef;
        min-height: auto;
    }
    .dpImg {
        border-radius: 100%;
    }
    <% end %>
</style>

<section>
  <% content_for :section do %>
      <%= render 'myworks' %>
      <div class="container">
        <div class="row">
          <div class="col-sm-2">
            <a href = "/dpMain.jpg">
              <img src="/dpMain.jpg" alt="Profile Picture" title="Mirza Sulman Baig" class="img-responsive dpImg" />
            </a>
          </div>
          <div class="col-sm-6">
            <h1 class="text-center">Mirza Sulman Baig</h1>
            <p class="text-justify">I am now a days, working as researcher in <a href="http://www.isip40.it/index.php?mod=01_Staff&file=Sulman" >Image and Signal Processing Lab (ISIP40)</a>, in <strong>DITEN, University of Genova, Italy.</strong>
              I am working towards research in multi-person detection and tracking in crowd.
              I am using this information to further detect and analyze the crowd emotions.<a href="https://www.youtube.com/channel/UCkecwtFwuPlVPKUhgI8bzvw" >(LINK)</a></p>
            <p class="text-justify">My interests are in learning is mostly any programming language. I have worked in C, C++, C#, JAVA, Android, HTML, CSS, Python,
              PHP, CUDA C, MATLAB, OpenCV, MySQL etc. Now a days I am working on OpenCV for image and video processing and learning R language for data-analysis.
              Out of my passion of programming, I am learning web application development using PHP, Ruby on Rails and soon by Python/Django.</p>
            <p class="text-justify">If anyone want to contact, feel free to contact me. You can find my contact information <%= link_to 'here ->', contact_path %></p>
            <div
            class="fb-like"
            data-share="true"
            data-width="450"
            data-show-faces="true">
            </div>
          </div>
          <div class="col-sm-4">
            <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/sulmanweb" data-widget-id="590969815415836672">Tweets by @sulmanweb</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
          </div>
        </div>
      </div>
  <% end %>
</section>

<script>
    <% content_for :scripts do %>
    <% end %>
</script>

app/views/pages/temp.html.erb
<% content_for :title, '' %>

<style>
    <% content_for :styles do %>
    <% end %>
</style>

<section>
  <% content_for :section do %>
  <% end %>
</section>

<script>
    <% content_for :scripts do %>
    <% end %>
</script>

app/views/pages/works.html.erb
<% content_for :title, 'My Works' %>
<section>
  <% content_for :section do %>
      <div class="container-fluid">
        <div class="row link-ex">

          <!-- Tweeter link -->
          <%= link_to "http://tweet.sulman.me/" do %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="offer offer-radius offer-primary">
                  <div class="shape">
                    <div class="shape-text">
                      new
                    </div>
                  </div>
                  <div class="offer-content">
                    <h3 class="lead">
                      Tweeter
                    </h3>
                    <p>
                      http://tweet.sulman.me/<br>
                      Twitter clone social network
                    </p>
                  </div>
                </div>
              </div>
          <% end %>

          <!-- note link -->
          <%= link_to "http://note.sulman.me/" do %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="offer offer-radius offer-primary">
                  <div class="shape">
                    <div class="shape-text">
                      new
                    </div>
                  </div>
                  <div class="offer-content">
                    <h3 class="lead">
                      Key-Note
                    </h3>
                    <p>
                      http://note.sulman.me/<br>
                      Note taking and sharing app.
                    </p>
                  </div>
                </div>
              </div>
          <% end %>

          <!-- socialbook link -->
          <%= link_to "http://social.sulman.me/" do %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="offer offer-radius offer-primary">
                  <div class="shape">
                    <div class="shape-text">
                      new
                    </div>
                  </div>
                  <div class="offer-content">
                    <h3 class="lead">
                      Socialbook
                    </h3>
                    <p>
                      http://social.sulman.me/<br>
                      Facebook clone social network
                    </p>
                  </div>
                </div>
              </div>
          <% end %>

          <!-- fotolib link -->
          <%= link_to "http://fotolib.sulman.me/" do %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="offer offer-radius offer-primary">
                  <div class="offer-content">
                    <h3 class="lead">
                      FotoLib
                    </h3>
                    <p>
                      http://fotolib.sulman.me/<br>
                      Private photos managing and sharing app
                    </p>
                  </div>
                </div>
              </div>
          <% end %>

          <!-- SSN link -->
          <%= link_to "http://scholarshipnetwork.info/" do %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="offer offer-radius offer-primary">
                  <div class="offer-content">
                    <h3 class="lead">
                      Scholarship Network
                    </h3>
                    <p>
                      http://scholarshipnetwork.info/<br>
                      Scholarship posts website
                    </p>
                  </div>
                </div>
              </div>
          <% end %>

          <!-- stukdo link -->
          <%= link_to "http://stukdo.sulman.me/" do %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="offer offer-radius offer-primary">
                  <div class="offer-content">
                    <h3 class="lead">
                      Stukdo
                    </h3>
                    <p>
                      http://stukdo.sulman.me/<br>
                      A smart private todo list
                    </p>
                  </div>
                </div>
              </div>
          <% end %>

          <!-- estuk link -->
          <%= link_to "http://stukdo.sulman.me/" do %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="offer offer-radius offer-primary">
                  <div class="offer-content">
                    <h3 class="lead">
                      eStuk
                    </h3>
                    <p>
                      http://estuk.sulman.me/<br>
                      Two sided bookstore like amazon
                    </p>
                  </div>
                </div>
              </div>
          <% end %>

          <!-- startup demo link -->
          <%= link_to "http://demo.sulman.me/" do %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="offer offer-radius offer-primary">
                  <div class="offer-content">
                    <h3 class="lead">
                      Startup Demo
                    </h3>
                    <p>
                      http://demo.sulman.me/<br>
                      Demo page for getting newsletters
                    </p>
                  </div>
                </div>
              </div>
          <% end %>

          <!-- google play link -->
          <%= link_to "https://play.google.com/store/search?q=sulman%20baig" do %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="offer offer-radius offer-primary">
                  <div class="offer-content">
                    <h3 class="lead">
                      My Android Apps
                    </h3>
                    <p>
                      https://play.google.com/store/search?q=sulman%20baig/
                    </p>
                  </div>
                </div>
              </div>
          <% end %>

        </div>
      </div>
  <% end %>
</section>